import type { AxiomTheme } from './types'

export const materialTheme: AxiomTheme = {
  colors: {
    primary: '#000000',
    ball: '#6366f1',
    ballLight: '#818cf8',
    onPrimary: '#ffffff',
    secondary: '#5f5e61',
    onSecondary: '#ffffff',
    tertiary: '#000000',
    error: '#ba1a1a',
    onError: '#ffffff',
    background: '#f9f9fa',
    surface: '#f9f9fa',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f3f3f4',
    surfaceContainer: '#eeeeef',
    surfaceContainerHigh: '#e8e8e9',
    surfaceContainerHighest: '#e2e2e3',
    surfaceVariant: '#e2e2e3',
    onSurface: '#1a1c1d',
    onSurfaceVariant: '#47464a',
    onBackground: '#1a1c1d',
    outline: '#78767b',
    outlineVariant: '#c8c5ca',
    secondaryContainer: '#e4e1e5',
    onSecondaryContainer: '#656467',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    shadow: '#000000',
    scrim: '#000000',
    inverseSurface: '#2f3032',
    inverseOnSurface: '#f0f0f1',
    inversePrimary: '#a8a8ab',
    surfaceDim: '#dadadc',
    surfaceBright: '#f9f9fa',
  },

  spacing: {
    xs: '0.25rem',
    sm: '0.5rem',
    md: '1rem',
    lg: '1.5rem',
    xl: '2rem',
    gutter: '16px',
    margin: '24px',
    buttonXsY: '1px',
    buttonXsX: '0.375rem',
    buttonSmY: '0.125rem',
    buttonSmX: '0.5rem',
    buttonMdY: '0.25rem',
    buttonMdX: '0.625rem',
    buttonLgY: '0.375rem',
    buttonLgX: '0.75rem',
    buttonXlY: '0.5rem',
    buttonXlX: '0.875rem',
    inputXsY: '0.125rem',
    inputXsX: '0.375rem',
    inputSmY: '0.25rem',
    inputSmX: '0.5rem',
    inputMdY: '0.375rem',
    inputMdX: '0.625rem',
    inputLgY: '0.5rem',
    inputLgX: '0.75rem',
    inputXlY: '0.625rem',
    inputXlX: '0.875rem',
    cardPadding: '1rem',
    cardGap: '0.75rem',
  },

  radius: {
    none: '0',
    xs: '0.125rem',
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '1rem',
    full: '9999px',
  },

  shadows: {
    elevation1: '0 1px 2px rgba(0, 0, 0, 0.08)',
    elevation2: '0 2px 6px rgba(0, 0, 0, 0.06)',
    elevation3: '0 4px 12px rgba(0, 0, 0, 0.04)',
    elevation4: '0 8px 24px rgba(0, 0, 0, 0.06)',
    elevation5: '0 12px 32px rgba(0, 0, 0, 0.08)',
    elevationDialog: '0 16px 48px rgba(0, 0, 0, 0.12)',
    elevationMenu: '0 4px 12px rgba(0, 0, 0, 0.08)',
    elevationTooltip: '0 2px 8px rgba(0, 0, 0, 0.1)',
  },

  borders: {
    width: '1px',
    color: '#c8c5ca',
    focusRing: '0 0 0 2px rgba(0, 0, 0, 0.2)',
  },

  typography: {
    fontDisplay: 'Geist',
    display: {
      fontFamily: 'Geist',
      fontSize: '36px',
      lineHeight: '40px',
      fontWeight: 600,
      letterSpacing: '-0.02em',
    },
    headlineLg: {
      fontFamily: 'Geist',
      fontSize: '24px',
      lineHeight: '32px',
      fontWeight: 600,
      letterSpacing: '-0.02em',
    },
    headlineLgMobile: {
      fontFamily: 'Geist',
      fontSize: '20px',
      lineHeight: '28px',
      fontWeight: 600,
    },
    headlineMd: {
      fontFamily: 'Geist',
      fontSize: '20px',
      lineHeight: '28px',
      fontWeight: 600,
      letterSpacing: '-0.01em',
    },
    headlineSm: {
      fontFamily: 'Geist',
      fontSize: '16px',
      lineHeight: '24px',
      fontWeight: 600,
    },
    bodyLg: {
      fontFamily: 'Geist',
      fontSize: '16px',
      lineHeight: '24px',
      fontWeight: 400,
    },
    bodyMd: {
      fontFamily: 'Geist',
      fontSize: '14px',
      lineHeight: '20px',
      fontWeight: 400,
    },
    bodySm: {
      fontFamily: 'Geist',
      fontSize: '12px',
      lineHeight: '16px',
      fontWeight: 400,
    },
    labelMd: {
      fontFamily: '"JetBrains Mono"',
      fontSize: '12px',
      lineHeight: '16px',
      fontWeight: 500,
      letterSpacing: '0.02em',
    },
  },
}

export const fluentTheme: AxiomTheme = {
  colors: {
    ...materialTheme.colors,
    primary: '#0078d4',
    ball: '#0078d4',
    ballLight: '#2899f5',
    onPrimary: '#ffffff',
    secondary: '#106ebe',
    onSecondary: '#ffffff',
    background: '#ffffff',
    surface: '#ffffff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f3f2f1',
    surfaceContainer: '#edebe9',
    surfaceContainerHigh: '#e1dfdd',
    surfaceContainerHighest: '#d2d0ce',
    surfaceVariant: '#e1dfdd',
    onSurface: '#1b1a19',
    onSurfaceVariant: '#605e5c',
    onBackground: '#1b1a19',
    outline: '#8a8886',
    outlineVariant: '#c8c6c4',
    secondaryContainer: '#deecf9',
    onSecondaryContainer: '#004578',
    error: '#d13438',
    onError: '#ffffff',
    errorContainer: '#fde7e9',
    onErrorContainer: '#6e0811',
  },
  spacing: {
    ...materialTheme.spacing,
    gutter: '12px',
    margin: '24px',
    cardPadding: '12px',
    cardGap: '8px',
  },
  radius: {
    ...materialTheme.radius,
    xs: '2px',
    sm: '2px',
    md: '4px',
    lg: '4px',
    xl: '8px',
    full: '9999px',
  },
  shadows: {
    elevation1: '0 0 2px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.14)',
    elevation2: '0 0 2px rgba(0, 0, 0, 0.12), 0 2px 4px rgba(0, 0, 0, 0.14)',
    elevation3: '0 0 3px rgba(0, 0, 0, 0.12), 0 4px 8px rgba(0, 0, 0, 0.14)',
    elevation4: '0 0 4px rgba(0, 0, 0, 0.12), 0 8px 16px rgba(0, 0, 0, 0.14)',
    elevation5: '0 0 5px rgba(0, 0, 0, 0.12), 0 12px 24px rgba(0, 0, 0, 0.14)',
    elevationDialog: '0 0 8px rgba(0, 0, 0, 0.12), 0 16px 48px rgba(0, 0, 0, 0.14)',
    elevationMenu: '0 0 4px rgba(0, 0, 0, 0.12), 0 4px 12px rgba(0, 0, 0, 0.14)',
    elevationTooltip: '0 0 2px rgba(0, 0, 0, 0.12), 0 2px 6px rgba(0, 0, 0, 0.14)',
  },
  borders: {
    ...materialTheme.borders,
    color: '#8a8886',
    focusRing: '0 0 0 2px #0078d4',
  },
  typography: {
    ...materialTheme.typography,
    fontDisplay: '"Segoe UI"',
    display: { ...materialTheme.typography.display, fontFamily: '"Segoe UI"' },
    headlineLg: { ...materialTheme.typography.headlineLg, fontFamily: '"Segoe UI"' },
    headlineLgMobile: { ...materialTheme.typography.headlineLgMobile, fontFamily: '"Segoe UI"' },
    headlineMd: { ...materialTheme.typography.headlineMd, fontFamily: '"Segoe UI"' },
    headlineSm: { ...materialTheme.typography.headlineSm, fontFamily: '"Segoe UI"' },
    bodyLg: { ...materialTheme.typography.bodyLg, fontFamily: '"Segoe UI"' },
    bodyMd: { ...materialTheme.typography.bodyMd, fontFamily: '"Segoe UI"' },
    bodySm: { ...materialTheme.typography.bodySm, fontFamily: '"Segoe UI"' },
    labelMd: { ...materialTheme.typography.labelMd, fontFamily: 'Consolas' },
  },
}

export const iosTheme: AxiomTheme = {
  colors: {
    ...materialTheme.colors,
    primary: '#007aff',
    ball: '#007aff',
    ballLight: '#3395ff',
    onPrimary: '#ffffff',
    secondary: '#5856d6',
    onSecondary: '#ffffff',
    background: '#f2f2f7',
    surface: '#ffffff',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f2f2f7',
    surfaceContainer: '#e5e5ea',
    surfaceContainerHigh: '#d1d1d6',
    surfaceContainerHighest: '#c7c7cc',
    surfaceVariant: '#e5e5ea',
    onSurface: '#000000',
    onSurfaceVariant: '#3c3c43',
    onBackground: '#000000',
    outline: '#c6c6c8',
    outlineVariant: '#e5e5ea',
    secondaryContainer: '#e5e5ff',
    onSecondaryContainer: '#1d1d5e',
    error: '#ff3b30',
    onError: '#ffffff',
    errorContainer: '#ffe5e5',
    onErrorContainer: '#8e0000',
  },
  spacing: {
    ...materialTheme.spacing,
    gutter: '16px',
    margin: '20px',
    cardPadding: '16px',
    cardGap: '12px',
  },
  radius: {
    ...materialTheme.radius,
    xs: '6px',
    sm: '8px',
    md: '10px',
    lg: '12px',
    xl: '16px',
    full: '9999px',
  },
  shadows: {
    elevation1: '0 0.5px 1px rgba(0, 0, 0, 0.04)',
    elevation2: '0 1px 3px rgba(0, 0, 0, 0.04)',
    elevation3: '0 2px 8px rgba(0, 0, 0, 0.04)',
    elevation4: '0 4px 16px rgba(0, 0, 0, 0.06)',
    elevation5: '0 8px 24px rgba(0, 0, 0, 0.08)',
    elevationDialog: '0 12px 40px rgba(0, 0, 0, 0.12)',
    elevationMenu: '0 4px 16px rgba(0, 0, 0, 0.06)',
    elevationTooltip: '0 1px 4px rgba(0, 0, 0, 0.06)',
  },
  borders: {
    ...materialTheme.borders,
    color: '#c6c6c8',
    focusRing: '0 0 0 3px rgba(0, 122, 255, 0.3)',
  },
  typography: {
    ...materialTheme.typography,
    fontDisplay: '"SF Pro Display"',
    display: { ...materialTheme.typography.display, fontFamily: '"SF Pro Display"', fontWeight: 700 },
    headlineLg: { ...materialTheme.typography.headlineLg, fontFamily: '"SF Pro Display"', fontWeight: 700 },
    headlineLgMobile: { ...materialTheme.typography.headlineLgMobile, fontFamily: '"SF Pro Display"', fontWeight: 700 },
    headlineMd: { ...materialTheme.typography.headlineMd, fontFamily: '"SF Pro Display"', fontWeight: 600 },
    headlineSm: { ...materialTheme.typography.headlineSm, fontFamily: '"SF Pro Display"', fontWeight: 600 },
    bodyLg: { ...materialTheme.typography.bodyLg, fontFamily: '"SF Pro Text"' },
    bodyMd: { ...materialTheme.typography.bodyMd, fontFamily: '"SF Pro Text"' },
    bodySm: { ...materialTheme.typography.bodySm, fontFamily: '"SF Pro Text"' },
    labelMd: { ...materialTheme.typography.labelMd, fontFamily: '"SF Mono"' },
  },
}
